# Generated by Django 4.2.1 on 2023-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales_data_AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('Region', models.CharField(max_length=30)),
                ('Regional_manager', models.CharField(max_length=30)),
                ('Head_quarter', models.CharField(max_length=30)),
                ('Business_executive', models.CharField(max_length=30)),
                ('Agency', models.CharField(max_length=200)),
                ('Product', models.CharField(max_length=60)),
                ('Billed_qty', models.IntegerField()),
                ('Billed_rate', models.IntegerField()),
                ('Company_value', models.IntegerField()),
            ],
        ),
    ]
