# Generated by Django 4.2.1 on 2023-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AP', '0002_alter_sales_data_ap_company_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_data_ap',
            name='Billed_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
