# Generated by Django 4.2.1 on 2023-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AP', '0003_alter_sales_data_ap_billed_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP_geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Head_quarters', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('P_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('P_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('C_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('C_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('H_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('H_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
    ]
